/*
 *  File: cards.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.3.0)
 *
 */

var fs = require('fs'),
    _ = require('underscore'),
    path = require('path');

module.exports = function(mongoose, conn, callback) {

    var initCards = JSON.parse(fs.readFileSync(path.resolve(__dirname, './cards-dump.json'), 'UTF-8'));

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];

    _.each(initCards.cards, function(jcard) {
        var abilities = [];
        _.each(jcard.abilities, function(jability) {
            abilities.push(jability);
        });

        fixture.push({
            title: jcard.title,
            category: jcard.category,
            image_url: jcard.image_url,
            content: jcard.content,
            abilities: abilities,
            attack: jcard.attack,
            health_power: jcard.health_power,
            cost: jcard.cost,
            rare: jcard.rare,
            occupation: jcard.occupation,
            race: jcard.race,
            evaluation: jcard.evaluation
        });
    });

    return callback(error, fixture);
};
