/*
 *  File: users.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.3.0)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']
// mongoose is the instance of mongoose being used (has schemas)
// conn is the current native mongodb connection (will contain models)

var hsHelper = require('../common/hearthstoneHelper');

module.exports = function(mongoose, conn, callback){

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];

    /*
     * Example of adding a data document/fixture item
     */
    fixture.push({
        name:'tim',
        pass: '270f8b9d8bdf7210230d4f9af1dcfede',
        email: 'tang.jilong@gmail.com',
        avatar: 'http://timtang.me',
        deviceToken: '00000000'
    });

    // mongoose-fixture expects implementor to return
    // the callback passed in context
    return callback(error, fixture);
};
