
/*
 *  File: versions.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.3.0)
 *
 */

var _ = require('underscore'),
cardSchema = require('../model/card');

module.exports = function(mongoose, conn, callback) {

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];
    var Card = conn.model('Card', cardSchema(mongoose));
    Card.find({},function(err, cards){
        var cardIds = [];
        _.each(cards, function(card) {
            cardIds.push(card._id);
        });

        fixture.push({
            version_no: 0,
            card_ids: cardIds
        });
        return callback(error, fixture);
    });
};
