/*
 *  File: versions.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.3.0)
 *
 */

var cardService = require('../service').CardService,
    _ = require('underscore');

module.exports = function(mongoose, conn, callback) {

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];
    cardService.getAllCards(function(err, cards) {
        var cardIds = [];
        _.each(cards, function(card) {
            cardIds.push(card._id);
        });

        fixture.push({
            version_no: 0,
            card_ids: cardIds
        });
        return callback(error, fixture);
    });
};
